# Generated by Django 4.1.7 on 2023-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0009_alter_city_country_alter_country_conitnent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWeather9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('sky', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
