# Generated by Django 4.1.7 on 2023-04-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0010_timeweather_timeweather12_timeweather15_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='continent_img',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='status_icon',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='weather_status',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='dateweather',
            name='attent_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeRise',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeSet',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather', to='weather_app.timeweather'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather12', to='weather_app.timeweather12'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather15', to='weather_app.timeweather15'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather20', to='weather_app.timeweather20'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather23', to='weather_app.timeweather23'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather6', to='weather_app.timeweather6'),
        ),
        migrations.AddField(
            model_name='dateweather',
            name='timeWeather9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeweather9', to='weather_app.timeweather9'),
        ),
    ]
